Добавлен интерфейс для редактирования организаций в кураторских группах
devind-team/dcis pull request #971
Opened 2022-11-02 19:16 UTC by MiloslavskiySergey

2022-11-02 20:19 UTC, Luferov requested changes

2022-11-03 09:43 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +      watchOnce(() => form.value.active, (value: boolean) => {
что подразумевается под проще?

2022-11-03 09:46 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +  width="1500"
из-за того что  названия организаций длинные, то при меньше 1500 названия организация выводятся в 2 строки и это не очень красиво получается

2022-11-03 09:49 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +        )
не понял?

2022-11-03 09:52 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +      newOrganizationsValidationProvider.value.reset()
не понял?

2022-11-03 09:52 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +        variables: () => {
почему?

2022-11-03 10:01 UTC, Luferov commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +      newOrganizationsValidationProvider.value.reset()
ну ты резетишь поле, а почему не резетишь всю форму?

2022-11-03 10:02 UTC, Luferov commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +  width="1500"
Ну вообще это глобальная проблема, да... нужно что-то делать

2022-11-03 10:03 UTC, Luferov commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +      watchOnce(() => form.value.active, (value: boolean) => {
ну просто watchOnce внутри onMounted не сильно ли сложно? Почему требуется именно такой алгоритм?

2022-11-03 10:37 UTC, MiloslavskiySergey commented on client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
> +      watchOnce(() => form.value.active, (value: boolean) => {
это нужно чтобы не делать лишних запросов, те запрос включается когда закрывается диалог

2022-11-03 12:20 UTC, SquakR approved these changes

2022-11-03 12:22 UTC, Luferov approved these changes

2022-11-03 13:36 UTC, merged